apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{NAME}}
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./{{NAME}}/manifests
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
