name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux-amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install sudo
        run: apt-get update && apt-get install sudo
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      #- name: Install Nix
      #  uses: DeterminateSystems/nix-installer-action@main
      - name: Build manifests
        run: nix build
      - name: Push to registry
        run: |
          mkdir -p /etc/containers && cp policy.json /etc/containers/policy.json
          nix develop .#push -c skopeo copy --dest-username ${{ gitea.actor }} --dest-password ${{ secrets.PACKAGE_PUBLISH_TOKEN }} --dest-tls-verify oci:result/oci-image:latest docker://gitea.home.josephmartin.org/${{ gitea.actor }}/netserv
