name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux-amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install sudo
        run: apt-get update && apt-get install sudo
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      #- name: Install Nix
      #  uses: DeterminateSystems/nix-installer-action@main
      - run: nix build
      - run: mkdir -p /etc/containers && cp policy.json /etc/containers/policy.json
      - run: nix develop .#push -c bash -c "skopeo login --username ${{ gitea.actor }} --password ${{ secrets.GITEA_TOKEN }} --tls-verify gitea.home.josephmartin.org && skopeo copy oci:result/oci-image:latest docker://gitea.home.josephmartin.org/${{ gitea.actor }}/netserv"
