name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: linux-amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      #- uses: cachix/install-nix-action@v23
      #  with:
      #    nix_path: nixpkgs=channel:nixos-23.05
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix build
