name: Gitea Actions Demo
run-name: nix-build
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - run: nix build
