name: Build Container Image
run-name: nix-build
on: [push]

jobs:
  Build-Container-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Build manifests
        run: nix build
      - name: Push to registry
        env:
          ACTOR: "${{ github.actor }}"
          TOKEN: "${{ secrets.PACKAGE_PUBLISH_TOKEN }}"
        run: |
          ACTOR=${ACTOR,,}
          nix develop .#push -c skopeo copy --dest-username "$ACTOR" --dest-password "$TOKEN" --dest-tls-verify oci:result/oci-image:latest "docker://ghcr.io/$ACTOR/netserv"
